name: GitHub Contribution Snake

on:
  schedule:
    # Run the workflow every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Generate Snake
      uses: ethomson/contributors-snake@v1
      with:
        github_user: adxthyx
        output_path: output/github-contribution-snake.svg
        
    - name: Commit & Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Generate contribution snake" -a
        git push
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        keep_files: true
