name: Generate Snake

on:
  schedule:
    # Run the workflow every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout the branch you're working on, if not 'master'
        checkout-branch: master

    - uses: Platane/snk@master
      id: snake-gif
      with:
        github_user_name: MeghnaS21
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

    - name: Check status
      run: git status

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        force: true

    - uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
